import './globals.css'
import { Cabin } from 'next/font/google'
const aleo = Cabin({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${aleo.className} bg-slate-200`}>{children}</body>
    </html>
  )
}
